services:
  db:
    container_name: postgresdb
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # Bind mount from your Windows folder to Postgres data folder
      - C:/Users/ekol4/Desktop/FindMyHobby/Backup/db:/var/lib/postgresql/data
    command: -c logging_collector=on
