version: "3.9"

services:
  db:
    container_name: postgresdb
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Backup/db:/var/lib/postgresql/data
    command: -c logging_collector=on

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

  backend:
    container_name: flask-backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./backend:/app
  frontend:
    container_name: react-frontend
    build: ./frontend
    restart: always
    ports:
        - "5173:5173"
    depends_on:
        - backend


volumes:
  pgadmin_data:
